In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]
np.array(lst)

array([1, 2, 3, 4, 5])

In [3]:
lst

[1, 2, 3, 4, 5]

In [4]:
arr = np.array(lst)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr.shape

(5,)

### rows and columns

In [18]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,10]
lst3 = [2,4,6,8,12]

In [21]:
# arr1 = np.array((lst1,lst2,lst3))
arr1 = np.array([lst1,lst2,lst])

In [22]:
arr1.shape

(3, 5)

In [23]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

### Indexing

In [37]:
ar = np.array([1,2,3,4,5])

In [38]:
ar[3]

4

In [39]:
ar[2] = 50

In [40]:
ar

array([ 1,  2, 50,  4,  5])

In [41]:
ar[1:]

array([ 2, 50,  4,  5])

In [42]:
ar[1:3]

array([ 2, 50])

In [43]:
ar[-1]

5

In [45]:
ar = np.array([1,2,3,4,5])

In [48]:
ar[:0]

array([], dtype=int64)