In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
# Data Structure: [resturant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1,150000, 180000, 220000, 250000], # Paradise Biryani
    [2,120000, 140000, 160000, 190000], # Bhejing Bites
    [3,200000, 230000, 260000, 300000], # Pizza Hub
    [4,180000, 210000, 240000, 270000], # Burger Point
    [5,160000, 180000, 205000, 230000], # Chai Point
])
print("=== Zomoto sales analysis ===")
print("\n Sales Data Shape: ", sales_data.shape)
print("\nSample Data for 1st 3 Resturant: \n",sales_data[:,1:])
print("\nSample Data for 1st 3 Resturant: \n",sales_data[:,1:5])
# print("\nSample Data for 1st 3 Resturant: \n",sales_data[:3])
# print("\nSample Data for 1st 3 Resturant: \n",sales_data[0:3])
# print("\nSample Data for 1st 3 Resturant: ",sales_data[3])

=== Zomoto sales analysis ===

 Sales Data Shape:  (5, 5)

Sample Data for 1st 3 Resturant: 
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 180000 205000 230000]]

Sample Data for 1st 3 Resturant: 
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 180000 205000 230000]]


In [ ]:
# Total Sales per year
# print(sales_data[0:3, 0:5])
print(np.sum(sales_data, axis=0))
yearly_total = np.sum(sales_data[:, 1:], axis=0)
print(yearly_total)
# total_sales = np.sum(sales_data[:, 1:], axis=0)
# print("\nTotal Sales per Year (2021 to 2024): ", total_sales)

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
