### Numpy Array Operations 

In [36]:
import numpy as np 

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# arr = np.arange(10)
print("Basic Slicing: ", arr[2:7])
print("With Step: ", arr[1:8:2])
print("Negative Indexing : ", arr[-3])

Basic Slicing:  [3 4 5 6 7]
With Step:  [2 4 6 8]
Negative Indexing :  8


In [37]:
arr_2d = np.array([[1,2,3], # 0 row [1,2,3] => 0, 1, 2
                   [4,5,6], # 1 row
                   [7,8,9]]) # 2 row
print("Specific Element: ", arr_2d[1, 2])
print("Entire Row: ", arr_2d[0]) # first entire row [1,2,3]
print("Entire Row: ", arr_2d[1])# second entire row [3,4,5]
print("Entire Row: ", arr_2d[2])
print("Entire colm: ", arr_2d[:, 1]) # second enitre colm

Specific Element:  6
Entire Row:  [1 2 3]
Entire Row:  [4 5 6]
Entire Row:  [7 8 9]
Entire colm:  [2 5 8]


### Sorting

In [7]:
unsorted = np.array([3,5,1,2,7,4,8,9,6])
sorted_array = np.sort(unsorted)
print("Sorted Array: ", sorted_array)

arr_2d_unsorted = np.array([[3,1], [4, 2], [21, 3]])
arr_2d_sorted = np.sort(arr_2d_unsorted, axis=1)
print("\n2D Array Sorted: \n", arr_2d_sorted)

Sorted Array:  [1 2 3 4 5 6 7 8 9]

2D Array Sorted: 
 [[ 1  3]
 [ 2  4]
 [ 3 21]]


### Filter

In [8]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("even Numbers: ", even_numbers)

even Numbers:  [ 2  4  6  8 10]


### Filter With Mask

In [9]:
mask = numbers > 5
print("Number greator than 5 ", numbers[mask])

Number greator than 5  [ 6  7  8  9 10]


### Fancy Indexing Vs np.where()

In [11]:
indieces = [0, 2, 4]
print("numbers: ", numbers[indieces])

where_results = np.where(numbers > 5)
print("Numpy Results: ", numbers[where_results])
# np.where() : where also is array but specific conditions

# condition_array = np.array = np.where(numbers > 5, numbers*2, numbers)
condition_array = np.array = np.where(numbers > 5, "true", "false")
# condition_array = np.array = np.where(numbers > 5, numbers*1, numbers)
# condition_array = np.array = np.where(numbers > 5, numbers, numbers)
print("Conditon Array: ", condition_array)


numbers:  [1 3 5]
Numpy Results:  [ 6  7  8  9 10]
Conditon Array:  ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [1]:
# ---------------- or ----------------
# if (numbers > 5) {
#     numbers * 4
# }
# else {
#     numbers
# }


### Adding and Removing Data

In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# combined = arr1 + arr2
combined = np.concatenate((arr1, arr2))

print(combined)


[1 2 3 4 5 6]


### Array Compatibility

In [34]:
a = np.array([1, 2, 3])
# b = np.array([4, 5, 6])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility Shapes: ", a.shape == b.shape)

Compatibility Shapes:  False


In [ ]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([5, 6])
# vstack always add row
with_new_row = np.vstack((original, new_row))
print(original, "\n")
print(with_new_row)

[[1 2]
 [3 4]] 

[[1 2]
 [3 4]
 [5 6]]
