### Storing Image in Matrix and Converting Image in Dark Mode

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [17]:
array1 = np.array([[1,2,3], [4,5,6]])
array2 = np.random.rand(3, 3)
array3 = np.zeros((4, 4))
print(array3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
np.save('array1.npy',array1)
np.save('array2.npy',array2)
np.save('array3.npy',array3)

In [19]:
loaded_array1 = np.load('array1.npy')
print(loaded_array1)

[[1 2 3]
 [4 5 6]]


In [ ]:
try: