## Numpy Array & Basics 

In [4]:
# No need to import numpy again as it is already used in the cells below.
import numpy as np


## Creating Array from List

In [6]:
arr_1d = np.array([1,2,3])
print("1D Array: ",arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D Array: ", arr_2d)

1D Array:  [1 2 3]
2D Array:  [[1 2 3]
 [4 5 6]]


## List Vs Numpy

In [ ]:
py_list = [1,2,3]
print("Python Multiplication: ", py_list * 2)

np_array = np.array([1,2,3]) #element wise multiplication
print("Python Array Multiplication: ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)
start = time.time()
# np_array = np.array()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python Multiplication:  [1, 2, 3, 1, 2, 3]
Python Array Multiplication:  [2 4 6]

 List operation time:  0.19561982154846191


### Creating Array from Scratch

In [ ]:
zeros = np.zeros((3,4)) # 3 => rows, 4 => Colm
print("\nZeros Array: \n",zeros)

one = np.ones((2,3))
print("\nOnes Array: \n",one)

#constant Values Array

full = np.full((2,2,), 7)
print("\nFull Array: \n",full)

random = np.random.random(((2,3)))
print("\nRandom Array: \n",random)

sequence = np.arange(0, 10, 2)
print("\nSequence: ",sequence)


### Vector , Matrix & Tensor

In [ ]:
vector = np.array([1,2,3])

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("\nMatrix: \n",matrix)

tensor = np.array([[[1,2], [4,5],
                    [6,7], [8,9]]])
print("\nTensor: \n",tensor)


### Array Properties

In [47]:
arr = np.array([[1,2,3],
               [4,5,6]])
print("Shape: ", arr.shape)
print("Dimention: ", arr.ndim) #Dimentions
print("Size: ", arr.size) 
print("Data Type: ", arr.dtype) 

Shape:  (2, 3)
Dimention:  2
Size:  6
Data Type:  int64


### Array Reshaping

In [59]:
arr = np.arange(12)
print("Original Array: ",arr)

reshape = arr.reshape((3,4))
print("\n Reshaped Array: \n",reshape)

flattenend = reshape.flatten() # return copy 
print("\nflattenend: \n",flattenend)

# Ravel (returns view, instead of copy): return original
raveled = reshape.ravel()
print("\nRaveled: \n",raveled)

# Transpose

transpose = reshape.transpose()
print("\nTranspose: \n",transpose)


Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

flattenend: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
