### Revision

In [1]:
import numpy as np

In [36]:
arr = np.array([1,2,3])
# print(arr)

arr2 = np.array(([1,2,3],[4,5,6],[7,8,9]))
# print(arr2,"\n")

# for i in arr2:
#     print(i)

# print("\nSqare of arr: \n", arr2 * 2)

transposeArray = arr2.T
# print(transposeArray)


zeroArray = np.zeros([3,3])
print(zeroArray, "\n")

onesArray = np.ones((3,3))
print(onesArray, "\n")

allArrayElement = np.full((3,4), 7)
print(allArrayElement, "\n")

randomeArray = np.random.random(((3,3)))
print(randomeArray, "\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]] 

[[0.30290822 0.46259649 0.78461035]
 [0.88364132 0.79033817 0.82445864]
 [0.70162525 0.25797476 0.57645779]] 



In [46]:
# arrRange = np.arange(0, 10+1)
arrRange = np.arange(0, 10, 2)
# print(arrRange + 1)
print(arrRange )

[0 2 4 6 8]


In [ ]:
matrixArray = np.